Add Citra RNG Setup Guide
zaksabeast/PokemonRNGGuides pull request #125
Opened 2021-02-24 01:11 UTC by ShinySylveon04

# Guide Details

## I want to (select one)

- [x] Add a guide
- [ ] Modify an existing guide

## Games affected

- Gen 6 and 7 for Citra

## Type of RNG

- Setting up CitraRNG

## Language

- English

2021-03-14 13:55 UTC, zaksabeast requested changes
Just a few one word changes and a question or two.

2021-03-14 13:55 UTC, zaksabeast commented on guides/Citra and 3DS/CitraRNG Setup.md
> +  - In the install selection add python to your `PATH`
I'm not sure most people are going to know what `PATH` is referring to.  Doesn't this happen automatically with windows?  Or is this referring to the installer?

2021-03-14 13:55 UTC, zaksabeast commented on guides/Citra and 3DS/CitraRNG Setup.md
> +4. Exit back to Godemode9 main menu and select `scripts...` once more.
```suggestion
4. Exit back to the GodMode9 main menu and select `scripts...` once more.
```

2021-03-14 13:55 UTC, zaksabeast commented on guides/Citra and 3DS/CitraRNG Setup.md
> +   - Select `Dump_PKMN_Updates` script and follow the on screen directions
This looks like a sequential instruction:
4. Go to GodMode9 scripts
5. Select the `Dump_PKMN_Updates` script
6. Dump the game

Should this line be part of the numbered sequence?

2021-03-14 13:55 UTC, zaksabeast commented on guides/Citra and 3DS/CitraRNG Setup.md
> +   - Select `Build CIA (standard)`
This first line sounds more like a header than part of the sequential list of instructions, and it reads a bit odd to have a numbered header, but the actual instructions are in a bulleted list.

The title of this section is "Dumping system and game data".  What are thoughts on splitting it up into "Dumping system data" and "Dumping game data", then having the bullets of steps 6 and 7 be part of "Dumping game data"?

2021-03-14 13:55 UTC, zaksabeast commented on guides/Citra and 3DS/CitraRNG Setup.md
> +## Dumping system and game data
I think citra-emu.org has guides for this.  Should we link to them instead of writing out our own instructions?

Part of our Tools includes "Citra", which implies someone already has Citra installed and set up - listing Citra's official guides as bullets to that might be good.

2021-03-14 13:55 UTC, zaksabeast commented on guides/Citra and 3DS/CitraRNG Setup.md
> +Python 3.9 needs to be installed for CitraRNG to work. Python also needs to be added to your `Path` or else the command will not be recognized. If it's not installed then it can be added by editing t
Whoops, looks like PATH was accidentally not capitalized
```suggestion
Python 3.9 needs to be installed for CitraRNG to work. Python also needs to be added to your `PATH` or else the command will not be recognized. If it's not installed then it can be added by editing the installation.
```

I'm wondering if we should reword this a bit.  At the moment, it sounds like if Python is not installed, then it can be added by editing the installation, but what installation is there to edit if it's not installed?

2021-03-14 13:55 UTC, zaksabeast commented on guides/Citra and 3DS/CitraRNG Setup.md
> +3. Open Citra and your Gen 7 Pokémon game, and load your save file.
```suggestion
3. Open Citra and your Gen 7 Pokémon game, then load your save file.
```

2021-03-14 13:55 UTC, zaksabeast commented on guides/Citra and 3DS/CitraRNG Setup.md
> +Note: The higher the delay for the refresh rate the less often the program will crash, 2000 is max. Pause and reconnect CitraRNG every once in a while, to keep it from crashing.
```suggestion
Note: The higher the delay for the refresh rate the less often the program will crash, 2000 is the max. Pause and reconnect CitraRNG every once in a while, to keep it from crashing.
```

2021-04-27 13:45 UTC, RichardPaulAstley requested changes

2021-04-27 13:45 UTC, RichardPaulAstley commented on guides/Citra and 3DS/CitraRNG Setup.md
> +1. Open a command prompt anywhere and type `pip install pyside2`.
Only thing i'll be picky on, since last versions use pyside6

2021-05-18 17:21 UTC, RichardPaulAstley approved these changes

2021-08-02 21:56 UTC, merged