Edit USUM Wormhole guide
zaksabeast/PokemonRNGGuides pull request #127
Opened 2021-03-05 19:03 UTC by ShinySylveon04

# Guide Details

## I want to (select one)

- [ ] Add a guide
- [x] Modify an existing guide

## Games affected

- USUM

## Type of RNG

- Wormhole RNG

## Language

- English

## Notes

This PR will be a draft not ready for review until PR #124 is merged and this guide updated afterwards

2021-03-14 13:16 UTC, zaksabeast requested changes
One tiny change, but otherwise good to go.

2021-03-14 13:16 UTC, zaksabeast commented on guides/Ultra Sun and Ultra Moon/Stationary Wormhole RNG.md
> +- [3DSRNGTool README](https://github.com/wwwwwwzx/3DSRNGTool/blob/master/README.md#final-screen) - list of final screens before the Pokemon is generated
```suggestion
- [3DSRNGTool README](https://github.com/wwwwwwzx/3DSRNGTool/blob/master/README.md#final-screen) - list of final screens before Pokemon are generated
```

2021-08-04 20:21 UTC, RichardPaulAstley requested changes

2021-08-04 20:21 UTC, RichardPaulAstley commented on guides/Ultra Sun and Ultra Moon/Stationary Wormhole RNG.md
>  ## Step 1: Finding your seed
I'd add a note that it works for UBs too ?

2021-08-04 20:21 UTC, RichardPaulAstley commented on guides/Ultra Sun and Ultra Moon/Stationary Wormhole RNG.md
Well, it's not exactly where I want this note to be but whatever : 

In the step 2) when the subject of repeating it, it'd be important to add a note for the Legendaries : Being precise and doing the same type of input (direction / pressure) will help to have a stable delay. The idea is that the last input is a step done by the stick. So not really accurate. So it's important to always do the same kind of input.

2021-08-04 23:16 UTC, RichardPaulAstley approved these changes

2021-08-05 17:33 UTC, merged