Add Emerald Egg RNG Guide
zaksabeast/PokemonRNGGuides pull request #128
Opened 2021-03-05 19:05 UTC by ShinySylveon04

# Guide Details

## I want to (select one)

- [x] Add a guide
- [ ] Modify an existing guide

## Games affected

- Emerald

## Type of RNG

- Egg RNG

## Language

- English

2021-03-11 20:20 UTC, ShinySylveon04 commented
This guide needs to be updated for latest PokeFinder before it can be reviewed.

2021-03-15 00:07 UTC, ShinySylveon04 commented
Update: Guide has been edited and is ready for review

2021-08-04 23:35 UTC, RichardPaulAstley requested changes

2021-08-04 23:35 UTC, RichardPaulAstley commented on guides/Ruby, Sapphire, and Emerald/Emerald Egg RNG.md
> +    - The first parent deposited will be Parent A, and the second parent deposited will be Parent B
Don't be a bad guy, don't use everstone

2021-08-04 23:35 UTC, RichardPaulAstley commented on guides/Ruby, Sapphire, and Emerald/Emerald Egg RNG.md
> +3. Find your delay using `Target Advance - Advance Hit = Delay`.
Basic value : 18 (+/- 1 frame because of save and PokeFinder update) but you have to do that INSIDE the daycare. Always.

2021-08-04 23:35 UTC, RichardPaulAstley commented on guides/Ruby, Sapphire, and Emerald/Emerald Egg RNG.md
> +3. Find your delay using `Target Advance - Advance Hit = Delay`.
Default : 3 always +/- 1 because PokeFinder blablablablabla

2021-08-06 19:25 UTC, RichardPaulAstley requested changes

2021-08-06 19:25 UTC, RichardPaulAstley commented on guides/Emerald/Egg RNG.md
> +   - If still no egg, take a step 19 advances before your target advance.
i'd not have removed what you've done explaining how to find the delay, but the idea is more to give a default value

2021-08-06 19:39 UTC, RichardPaulAstley approved these changes

2021-08-06 19:43 UTC, merged