Edit Timeline Leap guides
zaksabeast/PokemonRNGGuides pull request #131
Opened 2021-03-09 21:20 UTC by ShinySylveon04

# Guide Details

## I want to (select one)

- [ ] Add a guide
- [x] Modify an existing guide

## Games affected

- Sun/Moon/Ultra Sun/Ultra Moon

## Type of RNG

- Timeline Leap

## Language

- English

## Notes

This will close issue #123.

2021-03-14 13:28 UTC, zaksabeast requested changes
Sorry, I know you were just modifying formatting and my changes are more about the content.  Just a few small changes, but otherwise looks great.

I only suggested changes for the SM guide, but most changes should be reflects into the USUM guide.

2021-03-14 13:28 UTC, zaksabeast commented on guides/Sun and Moon/Timeline Leap Guide.md
> +slug: 'retail-usum-timeleap'
Was this an intentional change to have one timeleap url?

If not, we may want to change it back:
```suggestion
slug: 'retail-sm-timeleap'
```

2021-03-14 13:28 UTC, zaksabeast commented on guides/Sun and Moon/Timeline Leap Guide.md
> +1. Input the current frame you are on after confirming it is a safe frame into the starting frame in "Frame Range".
```suggestion
1. After confirming your current frame is a safe frame, input it into the "Frame Range" starting frame.
```

2021-03-14 13:28 UTC, zaksabeast commented on guides/Sun and Moon/Timeline Leap Guide.md
> +2. Then choose "Timeline Leap" and click on "Calculate".
```suggestion
2. Choose "Timeline Leap" and click on "Calculate"
```

2021-03-14 13:28 UTC, zaksabeast commented on guides/Sun and Moon/Timeline Leap Guide.md
> +   - Choose "No" will allow you to check if there are any other Frame 1 that can make Frame 2 have the spread you wanted.
```suggestion
   - Choosing "No" will allow you to check if there are any other Frame 1 that can make Frame 2 have the spread you wanted.
```

2021-03-14 19:41 UTC, RichardPaulAstley requested changes

2021-03-14 19:41 UTC, RichardPaulAstley commented on guides/Sun and Moon/Timeline Leap Guide.md
>  ## Step 2: Advance frames
I don't see any comment about when you should leave the Festival Plaza / Mall to start the timeleap process

2021-03-14 19:41 UTC, RichardPaulAstley commented on guides/Sun and Moon/Timeline Leap Guide.md
>  Since you can jump between different timelines by choosing the leap timing, you can land on any frame of your choosing.
Also a way to say that it's not doable on wild stuff to be 100% complete ?

2021-03-14 19:41 UTC, RichardPaulAstley commented on guides/Ultra Sun and Ultra Moon/Timeline Leap Guide.md
>  ## Step 2: Advance frames
Same as USUM

2021-03-14 19:41 UTC, RichardPaulAstley commented on guides/Ultra Sun and Ultra Moon/Timeline Leap Guide.md
>  Since you can jump between different timelines by choosing the leap timing, you can land on any frame of your choosing.
Maybe a note for some cases that are really unstable like Poipole. 
Also a way to say that it's not doable on wild stuff to be 100% complete ?

2021-08-04 23:15 UTC, RichardPaulAstley approved these changes

2021-08-05 18:00 UTC, closed without merging