Add notifications
zaksabeast/PokemonRNGGuides pull request #155
Opened 2021-08-30 18:06 UTC by ShinySylveon04

This PR adds notifications to the site so visitors can see what the latest changes are.

2021-09-05 20:10 UTC, RichardPaulAstley approved these changes

2021-09-12 01:51 UTC, zaksabeast requested changes

2021-09-12 01:51 UTC, zaksabeast commented on src/components/notifications.js
> +
Let's remove this empty line.

2021-09-12 01:51 UTC, zaksabeast commented on src/components/notification-list.js
> +                <List className={classes.list}>
It looks like `yarn format` needs to be run.

2021-09-12 01:51 UTC, zaksabeast commented on src/components/notifications.js
> +const messageList = orderBy(messages, ['date'], ['desc']);
I don't think the args need to be arrays.
```suggestion
const messageList = orderBy(messages, 'date', 'desc');
```

2021-09-12 01:51 UTC, zaksabeast commented on src/components/notification-list.js
> +                      ) : null}
We don't need to return null:
```suggestion
                      {index < messageList.length - 1 && (
                        <Divider className={classes.divider} />
                      )}
```

2021-09-12 01:51 UTC, zaksabeast commented on src/components/notification-list.js
> +                            )}
Pulling this out as a named function could help make it easier to read this component when skimming through it.

2021-09-12 01:51 UTC, zaksabeast commented on src/components/notification-list.js
> +                            id="notification-message"
Let's remove this Id since Ids should be unique and we're going to be rendering multiple components that use it.

2021-09-12 01:51 UTC, zaksabeast commented on src/components/notifications.js
> +            }}
Not a necessary change, but it would help make the code a bit more succinct.
```suggestion
            onClickAway={() => setPopperOpen(false)}
```

2021-09-12 01:51 UTC, zaksabeast commented on src/components/notification-list.js
> +                        alignItems="flex-start"
Since this prop is style related, I think we should move this to `classes.listItem`.  Props like this are convenient to avoid the boilerplate of `classes`, but it's confusing to mix both props and classes.

For example, if someone adds `alignItems: 'flexEnd'` to `classes.listItem`, which style will be used?  One of the two places wouldn't work as expected, and it might not be obvious where to look for this type of bug.

2021-09-17 01:58 UTC, zaksabeast requested changes
Looks good, getting super close!

2021-09-17 01:58 UTC, zaksabeast commented on src/components/notification-list.js
> +  };
Oh sorry, I meant pull this outside of the component.

When React checks which components it needs to update, it will check if a component's props have updated by comparing the current props to the previous props.  When a function lives inside of a component, a new function is effectively created each time the component is rendered, which means the function has a new reference in memory.  If this function is used as a prop for a component, it will always appear as if the props have changed, which will hurt performance.

As a result, it's generally good practice for functions to live outside of components when possible to prevent this from happening.  That won't happen in this case, but it's good to exercise that muscle when possible so it's instinctive when that situation does come up.

Also, there's not really a need for it to exist inside of the component, so the component itself will have less code.

2021-09-17 01:58 UTC, zaksabeast commented on src/components/notification-list.js
> +            </ListItem>
Not necessary, but pulling this into a `NotificationListItem` or `NotificationItem` component might be good for a separation of concerns.

2021-09-21 02:02 UTC, zaksabeast approved these changes

2021-10-04 15:46 UTC, merged