[Guide] Add BDSP Stationary RNG Guide
zaksabeast/PokemonRNGGuides pull request #185
Opened 2021-12-02 15:46 UTC by ShinySylveon04

This guide still needs a CaptureSight Install guide before merging, but it can be reviewed for the RNG.

2021-12-02 18:48 UTC, RichardPaulAstley requested changes

2021-12-02 18:48 UTC, RichardPaulAstley commented on guides/Brilliant Diamond and Shining Pearl/Stationary RNG.md
> +
-- Everything is not necessary here. I'd change that for the intro of the rough draft guide.

2021-12-02 18:48 UTC, RichardPaulAstley commented on guides/Brilliant Diamond and Shining Pearl/Stationary RNG.md
> +```
100% good we'll push screen once we can

2025-02-14 19:04 UTC, zaksabeast commented
Added in 0abbfb95780b13552201a908ea1963c3f6c5b656.

2025-02-14 19:04 UTC, closed without merging