Add CaptureSight install guide
zaksabeast/PokemonRNGGuides pull request #186
Opened 2021-12-06 18:12 UTC by ShinySylveon04

This PR adds a guide to installing CaptureSight for use with SwSh and BDSP RNG.

2021-12-06 18:21 UTC, RichardPaulAstley approved these changes

2021-12-06 18:21 UTC, RichardPaulAstley commented on guides/Tools and Emulators/CaptureSight Install.md
> +### Error: `dmnt:cht is not running`
I'd not put so big headers (when checking the file)

2021-12-08 13:01 UTC, zaksabeast requested changes

2021-12-08 13:01 UTC, zaksabeast commented on guides/Tools and Emulators/CaptureSight Install.md
> +- You are not using a game that CaptureSight supports. The list of supported games are as follows:
I'm not sure if 'as follows' is necessary:
```suggestion
- You are not using a game that CaptureSight supports. The list of supported games are:
```

Should we send users to the CaptureSight readme to see which games area available, so there's only one place to update?  I'm good if we want the list to live here, but updating one place is less work than two.

2021-12-09 01:49 UTC, merged