Update Using IPS Patches with Luma and Citra.md
zaksabeast/PokemonRNGGuides pull request #230
Opened 2024-02-16 18:13 UTC by Efadd

# Guide Details

## I want to (select one)

- [ ] Add a guide
- [ ] Modify an existing guide

## Games affected

- List all affected games here
- Add or remove bullets as needed

## Type of RNG

Describe the RNG - stationary, shadow, wild, egg, etc.

## Language

Please list the language your guide is written in.

## Notes

If needed, please make small notes here for extra details.

2024-02-16 18:18 UTC, Majora8120 commented
To add to this citra can load plugins for luma3ds without any modifications. With the current instructions it is not possible for people without any updates installed to a game to install the plugins.

2024-02-17 01:30 UTC, zaksabeast requested changes
Thanks for the update!  I think this guide was created when Citra first had ips support added, so it needs a good update.

2024-02-17 01:30 UTC, zaksabeast commented on guides/Tools and Emulators/Using IPS Patches with Luma and Citra.md
> +See Luma instructios, and the SDMC folder is the SD card.
Some people might not know what the SDMC folder is, and it might be easier to open a game's mod folder.

```suggestion
1. Right click a game
2. Click "Open Mods Location" to open the mods folder
3. Copy the `code.ips` file into the mods folder
```

2024-02-17 01:37 UTC, Efadd commented on guides/Tools and Emulators/Using IPS Patches with Luma and Citra.md
> +See Luma instructios, and the SDMC folder is the SD card.
Done, but Github mobile so took some attempts to get the phrasing. How does it look?

2024-02-17 03:24 UTC, zaksabeast requested changes
Just a few tiny changes.

2024-02-17 03:24 UTC, zaksabeast commented on guides/Tools and Emulators/Using IPS Patches with Luma and Citra.md
> +1. Right-click your game in Citra
Let's remove the hyphen in between 'right' and 'click':
```suggestion
1. Right click your game in Citra
```

2024-02-17 03:24 UTC, zaksabeast commented on guides/Tools and Emulators/Using IPS Patches with Luma and Citra.md
> +2. Select "Open Mods Location" to opsn the mods folder.
'open' is accidentally spelled incorrectly, and let's remove the full stop at the end of the line for consistency with the other lines in the file.
```suggestion
2. Select "Open Mods Location" to open the mods folder
```

2024-02-17 03:24 UTC, zaksabeast commented on guides/Tools and Emulators/Using IPS Patches with Luma and Citra.md
> +3. Copy your code.ips into the mods folder folder.
Let's add ticks around 'code.ips' to make it clear it's a file, remove the full stop, and remove the duplicate 'folder'.
```suggestion
3. Copy your `code.ips` into the mods folder
```

2024-02-17 03:25 UTC, Efadd commented on guides/Tools and Emulators/Using IPS Patches with Luma and Citra.md
> +3. Copy your code.ips into the mods folder folder.
Lemme open the file on github web so I can see it better...

2024-02-17 03:25 UTC, Efadd commented on guides/Tools and Emulators/Using IPS Patches with Luma and Citra.md
> +3. Copy your code.ips into the mods folder folder.
Lemme open the file on github web so I can see it better...

2024-02-17 03:26 UTC, zaksabeast commented on guides/Tools and Emulators/Using IPS Patches with Luma and Citra.md
> +See Luma instructios, and the SDMC folder is the SD card.
You should be able to see a "Commit suggestion" button under my suggested changes.  Clicking that will automatically make the exact suggested change without having to worry about formatting on mobile.

2024-02-17 03:27 UTC, Efadd commented on guides/Tools and Emulators/Using IPS Patches with Luma and Citra.md
> +3. Copy your code.ips into the mods folder folder.
Also, Merriam-Webster has the hyphen.

2024-02-17 03:29 UTC, Efadd commented on guides/Tools and Emulators/Using IPS Patches with Luma and Citra.md
> +See Luma instructios, and the SDMC folder is the SD card.
I don't see it, sorry

2024-02-17 03:31 UTC, zaksabeast commented on guides/Tools and Emulators/Using IPS Patches with Luma and Citra.md
> +3. Copy your code.ips into the mods folder folder.
Oh interesting - I learned something new today.

I'd still prefer keep it as "right click" for now since most of the site uses that spelling.

2024-02-17 03:32 UTC, zaksabeast approved these changes

2024-02-17 03:32 UTC, Efadd commented on guides/Tools and Emulators/Using IPS Patches with Luma and Citra.md
> +3. Copy your code.ips into the mods folder folder.
Done, and I do see the buttons on the website, but not on mobile, odd...

2024-02-17 03:33 UTC, merged